---
  name: Push AlphaFold3 image to GitHub Registry
  run-name: Pushing image after ${{ github.actor }}'s latest push

  on:
    push:
      branches:
        - main
  
  jobs:
    build:
      name: Build
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Registry Login
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            file: Dockerfile
            tags: | 
              ghcr.io/washu-it-ris/alphafold3_wustl_fork_agora_implementation:latest
